on:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: write

jobs:
  update_tap:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Get local tag
        id: localTag
        run: |
            echo "tag=`echo $(git describe --tags --abbrev=0)`"
            echo "tag=`echo $(git describe --tags --abbrev=0)`" >> "$GITHUB_OUTPUT"
      - name: Get upstream release
        id: upstreamRelease
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: small-hack/smol-k8s-lab

      - name: Update Release
        run: |
          sed -i 's/${{ steps.localTag.outputs.tag }}/${{ steps.upstreamRelease.outputs.release }}/g' ./Formula/smol-k8s-lab.rb
          cat ./Formula/smol-k8s-lab.rb
          git config --global user.email "jessebot@linux.com"
          git config --global user.name "jessebot"
          git commit -m "Updating latest package from ${{ steps.localTag.outputs.tag }} to ${{ steps.upstreamRelease.outputs.release }}" ./Formula/smol-k8s-lab.rb
          git push
          git tag ${{ steps.upstreamRelease.outputs.release }}
          git push --tags
